/home/i0179/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
Traceback (most recent call last):
  File "/home/i0179/Realitylab-site/ai_server/app.py", line 9, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2154, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2184, in _get_module
    raise e
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2182, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/i0179/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/i0179/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 38, in <module>
    from .auto_factory import _LazyAutoMapping
  File "/home/i0179/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 43, in <module>
    from ...generation import GenerationMixin
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2154, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2184, in _get_module
    raise e
  File "/home/i0179/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 2182, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/i0179/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/i0179/lib/python3.10/site-packages/transformers/generation/utils.py", line 130, in <module>
    from accelerate.hooks import AlignDevicesHook, add_hook_to_module
  File "/home/i0179/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/home/i0179/lib/python3.10/site-packages/accelerate/accelerator.py", line 38, in <module>
    from .big_modeling import _attach_context_parallel_hooks
  File "/home/i0179/lib/python3.10/site-packages/accelerate/big_modeling.py", line 25, in <module>
    from .hooks import (
  File "/home/i0179/lib/python3.10/site-packages/accelerate/hooks.py", line 23, in <module>
    from .utils import (
  File "/home/i0179/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 223, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/i0179/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 29, in <module>
    from ..big_modeling import dispatch_model, init_empty_weights
ImportError: cannot import name 'dispatch_model' from partially initialized module 'accelerate.big_modeling' (most likely due to a circular import) (/home/i0179/lib/python3.10/site-packages/accelerate/big_modeling.py)
